---
- hosts: serviceding.in.devtal.de
  vars_files:
  - vars/main.yml
  roles:
    - role: debian-common
      upgrade_unattended: false
      mirror: "{{debian_mirror}}"
    - role: cert
      cert_path: "{{apache_conf['cert_path']}}"
      cert_conf: /etc/ssl/apache-openssl-altname.cnf
      key_path: "{{apache_conf['key_path']}}"
      key_size: "{{apache_conf['key_size']}}"
      daemons: [ "apache2" ]
    - { role: apache-basic, apache: '{{ apache_conf }}' }
    - role: mete
      dest: "{{mete_dir}}"
    - role: apache-passenger-site
      apache: '{{ apache_conf }}'
      site_fqdn: '{{mete_hostname}}'
      app_path: '{{mete_dir}}'
      site_path: '{{mete_dir}}/public'
      site_short: 'mete'
